# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"3\n\rFeatureVector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x12\n\nrequest_id\x18\x02 \x01(\t\">\n\x13PredictBatchRequest\x12\'\n\x05items\x18\x01 \x03(\x0b\x32\x18.inference.FeatureVector\"~\n\nPrediction\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x1b\n\x13\x63lass_probabilities\x18\x02 \x03(\x02\x12\x1d\n\x15predicted_class_index\x18\x03 \x01(\x05\x12 \n\x18inference_latency_micros\x18\x04 \x01(\x03\"B\n\x14PredictBatchResponse\x12*\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x15.inference.Prediction\"\x12\n\x10ReadinessRequest\"9\n\x11ReadinessResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x15\n\rmodel_version\x18\x02 \x01(\t2\xb0\x01\n\x10InferenceService\x12O\n\x0cPredictBatch\x12\x1e.inference.PredictBatchRequest\x1a\x1f.inference.PredictBatchResponse\x12K\n\x0e\x43heckReadiness\x12\x1b.inference.ReadinessRequest\x1a\x1c.inference.ReadinessResponseB2\n.com.prathamesh.inferencegateway.grpc.generatedP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.com.prathamesh.inferencegateway.grpc.generatedP\001'
  _globals['_FEATUREVECTOR']._serialized_start=30
  _globals['_FEATUREVECTOR']._serialized_end=81
  _globals['_PREDICTBATCHREQUEST']._serialized_start=83
  _globals['_PREDICTBATCHREQUEST']._serialized_end=145
  _globals['_PREDICTION']._serialized_start=147
  _globals['_PREDICTION']._serialized_end=273
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=275
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=341
  _globals['_READINESSREQUEST']._serialized_start=343
  _globals['_READINESSREQUEST']._serialized_end=361
  _globals['_READINESSRESPONSE']._serialized_start=363
  _globals['_READINESSRESPONSE']._serialized_end=420
  _globals['_INFERENCESERVICE']._serialized_start=423
  _globals['_INFERENCESERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
